// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASW8ttKLEo9C6kwCVlbgCT3Qduq4KghxA',
    appId: '1:803415926913:web:b65625b299bda25a15c580',
    messagingSenderId: '803415926913',
    projectId: 'dating-university-app',
    authDomain: 'dating-university-app.firebaseapp.com',
    storageBucket: 'dating-university-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdUg0I-NcDYbVRX9HO5K8j_sQkGXFOcsk',
    appId: '1:803415926913:android:434e08b646dd73bd15c580',
    messagingSenderId: '803415926913',
    projectId: 'dating-university-app',
    storageBucket: 'dating-university-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaPXSkHN54d_Qy3ZVXDZW_14pSu4hPkyc',
    appId: '1:803415926913:ios:6a0ed276e993533d15c580',
    messagingSenderId: '803415926913',
    projectId: 'dating-university-app',
    storageBucket: 'dating-university-app.appspot.com',
    iosBundleId: 'com.example.datingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaPXSkHN54d_Qy3ZVXDZW_14pSu4hPkyc',
    appId: '1:803415926913:ios:531268af38b8347215c580',
    messagingSenderId: '803415926913',
    projectId: 'dating-university-app',
    storageBucket: 'dating-university-app.appspot.com',
    iosBundleId: 'com.example.datingapp.RunnerTests',
  );
}
